#!/usr/bin/bash


A=$(wofi --show dmenu --width=100 --height=110 --prompt=Action cat << EOF
  Lock
  Exit Sway
  Reboot	
  Poweroff
EOF
)


case "$A" in
	
	*"Lock") swaylock -f -c 000000 --ring-color FFFFFF ;;
		
	*"Exit Sway") swaymsg exit;;

	*"Reboot") systemctl -i reboot;;

	*"Poweroff") systemctl -i poweroff ;;

esac

exit 0

